directories:
  output: release
  buildResources: build
appId: com.proedu1.whiteboard
productName: ProEdu1 Whiteboard
asar: false
win:
  target:
    - nsis
files:
  - filter:
      - electron/**/*
      - Server/**/*
      - '!Server/node_modules/**/*'
      - Client/dist/**/*
      - package.json
electronVersion: 28.3.3
